// Copyright 2025 The Lynx Authors. All rights reserved.
// Licensed under the Apache License Version 2.0 that can be found in the
// LICENSE file in the root directory of this source tree.

// Generated by the lynx template code generator.
// DO NOT EDIT!

#ifndef CORE_TEMPLATE_BUNDLE_TEMPLATE_CODEC_BINARY_DECODER_LYNX_CONFIG_DECODER_H_
#define CORE_TEMPLATE_BUNDLE_TEMPLATE_CODEC_BINARY_DECODER_LYNX_CONFIG_DECODER_H_

#include <memory>
#include <string>

#include "core/template_bundle/template_codec/binary_decoder/page_config.h"

namespace lynx {
namespace tasm {
class LynxConfigDecoder final {
 public:
  LynxConfigDecoder() = delete;
  ~LynxConfigDecoder() = delete;
  LynxConfigDecoder(const LynxConfigDecoder&) = delete;
  LynxConfigDecoder& operator=(const LynxConfigDecoder&) = delete;
  LynxConfigDecoder(LynxConfigDecoder&&) = delete;
  LynxConfigDecoder& operator=(LynxConfigDecoder&&) = delete;

  static inline void DecodePageConfig(std::shared_ptr<PageConfig>& page_config,
                                      const rapidjson::Document& doc,
                                      const std::string& target_sdk_version) {
    if (doc.HasMember(kVersion) && doc[kVersion].IsString()) {
      page_config->SetVersion(doc[kVersion].GetString());
    }

    if (doc.HasMember(kCliVersion) && doc[kCliVersion].IsString()) {
      page_config->SetCliVersion(doc[kCliVersion].GetString());
    }

    if (doc.HasMember(kReactVersion) && doc[kReactVersion].IsString()) {
      page_config->SetReactVersion(doc[kReactVersion].GetString());
    }

    if (doc.HasMember(kCustomData) && doc[kCustomData].IsString()) {
      page_config->SetCustomData(doc[kCustomData].GetString());
    }

    if (doc.HasMember(kTapSlop) && doc[kTapSlop].IsString()) {
      page_config->SetTapSlop(doc[kTapSlop].GetString());
    }

    if (doc.HasMember(kPreferredFps) && doc[kPreferredFps].IsString()) {
      page_config->SetPreferredFps(doc[kPreferredFps].GetString());
    }

    if (doc.HasMember(kLepusGCThreshold) && doc[kLepusGCThreshold].IsInt64()) {
      page_config->SetLepusGCThreshold(doc[kLepusGCThreshold].GetInt64());
    }

    if (doc.HasMember(kLogBoxImageSizeWarningThreshold) &&
        doc[kLogBoxImageSizeWarningThreshold].IsUint()) {
      page_config->SetLogBoxImageSizeWarningThreshold(
          doc[kLogBoxImageSizeWarningThreshold].GetUint());
    }

    if (doc.HasMember(kLepusQuickjsStacksize) &&
        doc[kLepusQuickjsStacksize].IsUint()) {
      page_config->SetLepusQuickjsStackSize(
          doc[kLepusQuickjsStacksize].GetUint());
    }

    if (doc.HasMember(kObserverFrameRate) && doc[kObserverFrameRate].IsInt()) {
      page_config->SetObserverFrameRate(doc[kObserverFrameRate].GetInt());
    }

    if (doc.HasMember(kLongPressDuration) && doc[kLongPressDuration].IsInt()) {
      page_config->SetLongPressDuration(doc[kLongPressDuration].GetInt());
    }

    if (doc.HasMember(kUseNewImage) && doc[kUseNewImage].IsBool()) {
      page_config->SetUseNewImage(doc[kUseNewImage].GetBool()
                                      ? TernaryBool::TRUE_VALUE
                                      : TernaryBool::FALSE_VALUE);
    }

    if (doc.HasMember(kEnableTextBoringLayout) &&
        doc[kEnableTextBoringLayout].IsBool()) {
      page_config->SetEnableTextBoringLayout(
          doc[kEnableTextBoringLayout].GetBool() ? TernaryBool::TRUE_VALUE
                                                 : TernaryBool::FALSE_VALUE);
    }

    if (doc.HasMember(kEnableTextLayerRender) &&
        doc[kEnableTextLayerRender].IsBool()) {
      page_config->SetEnableTextLayerRender(
          doc[kEnableTextLayerRender].GetBool() ? TernaryBool::TRUE_VALUE
                                                : TernaryBool::FALSE_VALUE);
    }

    if (doc.HasMember(kEnableUseMapBuffer) &&
        doc[kEnableUseMapBuffer].IsBool()) {
      page_config->SetEnableUseMapBuffer(doc[kEnableUseMapBuffer].GetBool()
                                             ? TernaryBool::TRUE_VALUE
                                             : TernaryBool::FALSE_VALUE);
    }

    if (doc.HasMember(kEnableFiberElementForRadonDiff) &&
        doc[kEnableFiberElementForRadonDiff].IsBool()) {
      page_config->SetEnableFiberElementForRadonDiff(
          doc[kEnableFiberElementForRadonDiff].GetBool()
              ? TernaryBool::TRUE_VALUE
              : TernaryBool::FALSE_VALUE);
    }

    if (doc.HasMember(kEnableOptPushStyleToBundle) &&
        doc[kEnableOptPushStyleToBundle].IsBool()) {
      page_config->SetEnableOptPushStyleToBundle(
          doc[kEnableOptPushStyleToBundle].GetBool()
              ? TernaryBool::TRUE_VALUE
              : TernaryBool::FALSE_VALUE);
    }

    if (doc.HasMember(kEnableTextLayoutCache) &&
        doc[kEnableTextLayoutCache].IsBool()) {
      page_config->SetEnableTextLayoutCache(
          doc[kEnableTextLayoutCache].GetBool() ? TernaryBool::TRUE_VALUE
                                                : TernaryBool::FALSE_VALUE);
    }

    if (doc.HasMember(kEnableUnifiedPipeline) &&
        doc[kEnableUnifiedPipeline].IsBool()) {
      page_config->SetEnableUnifiedPipeline(
          doc[kEnableUnifiedPipeline].GetBool() ? TernaryBool::TRUE_VALUE
                                                : TernaryBool::FALSE_VALUE);
    }

    if (doc.HasMember(kEnableUseContextPool) &&
        doc[kEnableUseContextPool].IsBool()) {
      page_config->SetEnableUseContextPool(doc[kEnableUseContextPool].GetBool()
                                               ? TernaryBool::TRUE_VALUE
                                               : TernaryBool::FALSE_VALUE);
    }

    if (doc.HasMember(kEnableCSSLazyImport) &&
        doc[kEnableCSSLazyImport].IsBool()) {
      page_config->SetEnableCSSLazyImport(doc[kEnableCSSLazyImport].GetBool()
                                              ? TernaryBool::TRUE_VALUE
                                              : TernaryBool::FALSE_VALUE);
    }

    if (doc.HasMember(kEnableNewAnimator) && doc[kEnableNewAnimator].IsBool()) {
      page_config->SetEnableNewAnimator(doc[kEnableNewAnimator].GetBool()
                                            ? TernaryBool::TRUE_VALUE
                                            : TernaryBool::FALSE_VALUE);
    }

    if (doc.HasMember(kEnableComponentAsyncDecode) &&
        doc[kEnableComponentAsyncDecode].IsBool()) {
      page_config->SetEnableComponentAsyncDecode(
          doc[kEnableComponentAsyncDecode].GetBool()
              ? TernaryBool::TRUE_VALUE
              : TernaryBool::FALSE_VALUE);
    }

    if (doc.HasMember(kMapContainerType) && doc[kMapContainerType].IsInt()) {
      page_config->SetMapContainerType(doc[kMapContainerType].GetInt());
    }

    if (doc.HasMember(kFlatten) && doc[kFlatten].IsBool()) {
      page_config->SetGlobalFlattern(doc[kFlatten].GetBool());
    }

    if (doc.HasMember(kImplicit) && doc[kImplicit].IsBool()) {
      page_config->SetGlobalImplicit(doc[kImplicit].GetBool());
    } else if (lynx::tasm::Config::IsHigherOrEqual(target_sdk_version,
                                                   LYNX_VERSION_2_0)) {
      page_config->SetGlobalImplicit(false);
    }

    if (doc.HasMember(kLepusStrict) && doc[kLepusStrict].IsBool()) {
      page_config->SetEnableLepusStrictCheck(doc[kLepusStrict].GetBool());
    }

    if (doc.HasMember(kLepusNullPropAsUndef) &&
        doc[kLepusNullPropAsUndef].IsBool()) {
      page_config->SetEnableLepusNullPropAsUndef(
          doc[kLepusNullPropAsUndef].GetBool());
    } else if (lynx::tasm::Config::IsHigherOrEqual(target_sdk_version,
                                                   LYNX_VERSION_1_6)) {
      page_config->SetEnableLepusNullPropAsUndef(true);
    }

    if (doc.HasMember(kDataStrictMode) && doc[kDataStrictMode].IsBool()) {
      page_config->SetDataStrictMode(doc[kDataStrictMode].GetBool());
    }

    if (doc.HasMember(kEnableAsyncDisplay) &&
        doc[kEnableAsyncDisplay].IsBool()) {
      page_config->SetEnableAsyncDisplay(doc[kEnableAsyncDisplay].GetBool());
    }

    if (doc.HasMember(kEnableImageDownsampling) &&
        doc[kEnableImageDownsampling].IsBool()) {
      page_config->SetEnableImageDownsampling(
          doc[kEnableImageDownsampling].GetBool());
    }

    if (doc.HasMember(kEnableNewImage) && doc[kEnableNewImage].IsBool()) {
      page_config->SetEnableNewImage(doc[kEnableNewImage].GetBool());
    }

    if (doc.HasMember(kEnableTextNonContiguousLayout) &&
        doc[kEnableTextNonContiguousLayout].IsBool()) {
      page_config->SetEnableTextNonContiguousLayout(
          doc[kEnableTextNonContiguousLayout].GetBool());
    }

    if (doc.HasMember(kEnableViewReceiveTouch) &&
        doc[kEnableViewReceiveTouch].IsBool()) {
      page_config->SetEnableViewReceiveTouch(
          doc[kEnableViewReceiveTouch].GetBool());
    }

    if (doc.HasMember(kEnableEventThrough) &&
        doc[kEnableEventThrough].IsBool()) {
      page_config->SetEnableEventThrough(doc[kEnableEventThrough].GetBool());
    }

    if (doc.HasMember(kRemoveComponentElement) &&
        doc[kRemoveComponentElement].IsBool()) {
      page_config->SetRemoveComponentElement(
          doc[kRemoveComponentElement].GetBool());
    }

    if (doc.HasMember(kStrictPropType) && doc[kStrictPropType].IsBool()) {
      page_config->SetStrictPropType(doc[kStrictPropType].GetBool());
    }

    if (doc.HasMember(kSyncImageAttach) && doc[kSyncImageAttach].IsBool()) {
      page_config->SetSyncImageAttach(doc[kSyncImageAttach].GetBool());
    }

    if (doc.HasMember(kUseImagePostProcessor) &&
        doc[kUseImagePostProcessor].IsBool()) {
      page_config->SetUseImagePostProcessor(
          doc[kUseImagePostProcessor].GetBool());
    }

    if (doc.HasMember(kUseNewSwiper) && doc[kUseNewSwiper].IsBool()) {
      page_config->SetUseNewSwiper(doc[kUseNewSwiper].GetBool());
    }

    if (doc.HasMember(kEnableAsyncInitVideoEngine) &&
        doc[kEnableAsyncInitVideoEngine].IsBool()) {
      page_config->SetEnableAsyncInitTTVideoEngine(
          doc[kEnableAsyncInitVideoEngine].GetBool());
    }

    if (doc.HasMember(kEnableComponentLifecycleAlignWebview) &&
        doc[kEnableComponentLifecycleAlignWebview].IsBool()) {
      page_config->SetEnableComponentLifecycleAlignWebview(
          doc[kEnableComponentLifecycleAlignWebview].GetBool());
    }

    if (doc.HasMember(kEnableListNewArchitecture) &&
        doc[kEnableListNewArchitecture].IsBool()) {
      page_config->SetListNewArchitecture(
          doc[kEnableListNewArchitecture].GetBool());
    }

    if (doc.HasMember(kEnableNewListContainer) &&
        doc[kEnableNewListContainer].IsBool()) {
      page_config->SetEnableNewListContainer(
          doc[kEnableNewListContainer].GetBool());
    }

    if (doc.HasMember(kEnableListPlug) && doc[kEnableListPlug].IsBool()) {
      page_config->SetEnableListPlug(doc[kEnableListPlug].GetBool());
    }

    if (doc.HasMember(kEnableListMoveOperation) &&
        doc[kEnableListMoveOperation].IsBool()) {
      page_config->SetEnableListMoveOperation(
          doc[kEnableListMoveOperation].GetBool());
    }

    if (doc.HasMember(kEnableCreateViewAsync) &&
        doc[kEnableCreateViewAsync].IsBool()) {
      page_config->SetEnableCreateViewAsync(
          doc[kEnableCreateViewAsync].GetBool());
    }

    if (doc.HasMember(kEnableVsyncAlignedFlush) &&
        doc[kEnableVsyncAlignedFlush].IsBool()) {
      page_config->SetEnableVsyncAlignedFlush(
          doc[kEnableVsyncAlignedFlush].GetBool());
    }

    if (doc.HasMember(kEnableAccessibilityElement) &&
        doc[kEnableAccessibilityElement].IsBool()) {
      page_config->SetEnableAccessibilityElement(
          doc[kEnableAccessibilityElement].GetBool());
    }

    if (doc.HasMember(kEnableOverlapForAccessibilityElement) &&
        doc[kEnableOverlapForAccessibilityElement].IsBool()) {
      page_config->SetEnableOverlapForAccessibilityElement(
          doc[kEnableOverlapForAccessibilityElement].GetBool());
    }

    if (doc.HasMember(kEnableNewAccessibility) &&
        doc[kEnableNewAccessibility].IsBool()) {
      page_config->SetEnableNewAccessibility(
          doc[kEnableNewAccessibility].GetBool());
    }

    if (doc.HasMember(kEnableNewLayoutOnly) &&
        doc[kEnableNewLayoutOnly].IsBool()) {
      page_config->SetEnableNewLayoutOnly(doc[kEnableNewLayoutOnly].GetBool());
    }

    if (doc.HasMember(kEnableReactOnlyPropsId) &&
        doc[kEnableReactOnlyPropsId].IsBool()) {
      page_config->SetEnableReactOnlyPropsId(
          doc[kEnableReactOnlyPropsId].GetBool());
    }

    if (doc.HasMember(kEnableGlobalComponentMap) &&
        doc[kEnableGlobalComponentMap].IsBool()) {
      page_config->SetEnableGlobalComponentMap(
          doc[kEnableGlobalComponentMap].GetBool());
    }

    if (doc.HasMember(kEnableTextRefactor) &&
        doc[kEnableTextRefactor].IsBool()) {
      page_config->SetEnableTextRefactor(doc[kEnableTextRefactor].GetBool());
    } else if (lynx::tasm::Config::IsHigherOrEqual(target_sdk_version,
                                                   LYNX_VERSION_2_2)) {
      page_config->SetEnableTextRefactor(true);
    }

    if (doc.HasMember(kEnableTextOverflow) &&
        doc[kEnableTextOverflow].IsBool()) {
      page_config->SetEnableTextOverflow(doc[kEnableTextOverflow].GetBool());
    } else if (lynx::tasm::Config::IsHigherOrEqual(target_sdk_version,
                                                   LYNX_VERSION_2_8)) {
      page_config->SetEnableTextOverflow(true);
    }

    if (doc.HasMember(kEnableNewClipMode) && doc[kEnableNewClipMode].IsBool()) {
      page_config->SetEnableNewClipMode(doc[kEnableNewClipMode].GetBool());
    } else if (lynx::tasm::Config::IsHigherOrEqual(target_sdk_version,
                                                   LYNX_VERSION_2_10)) {
      page_config->SetEnableNewClipMode(true);
    }

    if (doc.HasMember(kAutoResumeAnimation) &&
        doc[kAutoResumeAnimation].IsBool()) {
      page_config->SetGlobalAutoResumeAnimation(
          doc[kAutoResumeAnimation].GetBool());
    } else if (lynx::tasm::Config::IsHigherOrEqual(target_sdk_version,
                                                   LYNX_VERSION_2_3)) {
      page_config->SetGlobalAutoResumeAnimation(true);
    }

    if (doc.HasMember(kEnableNewTransformOrigin) &&
        doc[kEnableNewTransformOrigin].IsBool()) {
      page_config->SetGlobalEnableNewTransformOrigin(
          doc[kEnableNewTransformOrigin].GetBool());
    } else if (lynx::tasm::Config::IsHigherOrEqual(target_sdk_version,
                                                   LYNX_VERSION_2_6)) {
      page_config->SetGlobalEnableNewTransformOrigin(true);
    }

    if (doc.HasMember(kEnableCircularDataCheck) &&
        doc[kEnableCircularDataCheck].IsBool()) {
      page_config->SetGlobalCircularDataCheck(
          doc[kEnableCircularDataCheck].GetBool());
    }

    if (doc.HasMember(kEnableReduceInitDataCopy) &&
        doc[kEnableReduceInitDataCopy].IsBool()) {
      page_config->SetEnableReduceInitDataCopy(
          doc[kEnableReduceInitDataCopy].GetBool());
    }

    if (doc.HasMember(kEnableSimultaneousTap) &&
        doc[kEnableSimultaneousTap].IsBool()) {
      page_config->SetEnableSimultaneousTap(
          doc[kEnableSimultaneousTap].GetBool());
    }

    if (doc.HasMember(kEnableComponentLayoutOnly) &&
        doc[kEnableComponentLayoutOnly].IsBool()) {
      page_config->SetEnableComponentLayoutOnly(
          doc[kEnableComponentLayoutOnly].GetBool());
    } else if (lynx::tasm::Config::IsHigherOrEqual(target_sdk_version,
                                                   LYNX_VERSION_2_6)) {
      page_config->SetEnableComponentLayoutOnly(true);
    }

    if (doc.HasMember(kExtendedLayoutOnlyOpt) &&
        doc[kExtendedLayoutOnlyOpt].IsBool()) {
      page_config->SetEnableExtendedLayoutOpt(
          doc[kExtendedLayoutOnlyOpt].GetBool());
    } else if (lynx::tasm::Config::IsHigherOrEqual(target_sdk_version,
                                                   LYNX_VERSION_2_13)) {
      page_config->SetEnableExtendedLayoutOpt(true);
    }

    if (doc.HasMember(kEnableTouchRefactor) &&
        doc[kEnableTouchRefactor].IsBool()) {
      page_config->SetEnableTouchRefactor(doc[kEnableTouchRefactor].GetBool());
    }

    if (doc.HasMember(kEnableEndGestureAtLastFingerUp) &&
        doc[kEnableEndGestureAtLastFingerUp].IsBool()) {
      page_config->SetEnableEndGestureAtLastFingerUp(
          doc[kEnableEndGestureAtLastFingerUp].GetBool());
    }

    if (doc.HasMember(kDisableLongpressAfterScroll) &&
        doc[kDisableLongpressAfterScroll].IsBool()) {
      page_config->SetDisableLongpressAfterScroll(
          doc[kDisableLongpressAfterScroll].GetBool());
    }

    if (doc.HasMember(kKeyboardCallbackPassRelativeHeight) &&
        doc[kKeyboardCallbackPassRelativeHeight].IsBool()) {
      page_config->SetKeyboardCallbackUseRelativeHeight(
          doc[kKeyboardCallbackPassRelativeHeight].GetBool());
    } else if (lynx::tasm::Config::IsHigherOrEqual(target_sdk_version,
                                                   LYNX_VERSION_2_2)) {
      page_config->SetKeyboardCallbackUseRelativeHeight(true);
    }

    if (doc.HasMember(kEnableCheckDataWhenUpdatePage) &&
        doc[kEnableCheckDataWhenUpdatePage].IsBool()) {
      page_config->SetEnableCheckDataWhenUpdatePage(
          doc[kEnableCheckDataWhenUpdatePage].GetBool());
    }

    if (doc.HasMember(kEnableBackgroundShapeLayer) &&
        doc[kEnableBackgroundShapeLayer].IsBool()) {
      page_config->SetEnableBackgroundShapeLayer(
          doc[kEnableBackgroundShapeLayer].GetBool());
    }

    if (doc.HasMember(kCompileRender) && doc[kCompileRender].IsBool()) {
      page_config->SetCompileRender(doc[kCompileRender].GetBool());
    }

    if (doc.HasMember(kEnableTextLanguageAlignment) &&
        doc[kEnableTextLanguageAlignment].IsBool()) {
      page_config->SetEnableTextLanguageAlignment(
          doc[kEnableTextLanguageAlignment].GetBool());
    }

    if (doc.HasMember(kEnableXTextLayoutReused) &&
        doc[kEnableXTextLayoutReused].IsBool()) {
      page_config->SetEnableXTextLayoutReused(
          doc[kEnableXTextLayoutReused].GetBool());
    }

    if (doc.HasMember(kEnableRemoveComponentExtraData) &&
        doc[kEnableRemoveComponentExtraData].IsBool()) {
      page_config->SetEnableRemoveComponentExtraData(
          doc[kEnableRemoveComponentExtraData].GetBool());
    }

    if (doc.HasMember(kEnableExposureUIMargin) &&
        doc[kEnableExposureUIMargin].IsBool()) {
      page_config->SetEnableExposureUIMargin(
          doc[kEnableExposureUIMargin].GetBool());
    }

    if (doc.HasMember(kEnableNewGesture) && doc[kEnableNewGesture].IsBool()) {
      page_config->SetEnableNewGesture(doc[kEnableNewGesture].GetBool());
    }

    if (doc.HasMember(kEnableCheckLocalImage) &&
        doc[kEnableCheckLocalImage].IsBool()) {
      page_config->SetEnableCheckLocalImage(
          doc[kEnableCheckLocalImage].GetBool());
    }

    if (doc.HasMember(kEnableAsyncRequestImage) &&
        doc[kEnableAsyncRequestImage].IsBool()) {
      page_config->SetEnableAsyncRequestImage(
          doc[kEnableAsyncRequestImage].GetBool());
    }

    if (doc.HasMember(kEnableComponentNullProp) &&
        doc[kEnableComponentNullProp].IsBool()) {
      page_config->SetEnableComponentNullProp(
          doc[kEnableComponentNullProp].GetBool());
    }

    if (doc.HasMember(kEnableCascadePseudo) &&
        doc[kEnableCascadePseudo].IsBool()) {
      page_config->SetEnableCascadePseudo(doc[kEnableCascadePseudo].GetBool());
    }

    if (doc.HasMember(kAutoExpose) && doc[kAutoExpose].IsBool()) {
      page_config->SetAutoExpose(doc[kAutoExpose].GetBool());
    }

    if (doc.HasMember(kDisableQuickTracingGC) &&
        doc[kDisableQuickTracingGC].IsBool()) {
      page_config->SetDisableQuickTracingGC(
          doc[kDisableQuickTracingGC].GetBool());
    }

    if (doc.HasMember(kFixCSSImportRuleOrder) &&
        doc[kFixCSSImportRuleOrder].IsBool()) {
      page_config->SetFixCSSImportRuleOrder(
          doc[kFixCSSImportRuleOrder].GetBool());
    }

    if (doc.HasMember(kEnableReloadLifecycle) &&
        doc[kEnableReloadLifecycle].IsBool()) {
      page_config->SetEnableReloadLifecycle(
          doc[kEnableReloadLifecycle].GetBool());
    }

    if (doc.HasMember(kEnableA11y) && doc[kEnableA11y].IsBool()) {
      page_config->SetEnableA11y(doc[kEnableA11y].GetBool());
    }

    if (doc.HasMember(kEnableA11yIDMutationObserver) &&
        doc[kEnableA11yIDMutationObserver].IsBool()) {
      page_config->SetEnableA11yIDMutationObserver(
          doc[kEnableA11yIDMutationObserver].GetBool());
    }

    if (doc.HasMember(kEnableCheckExposureOptimize) &&
        doc[kEnableCheckExposureOptimize].IsBool()) {
      page_config->SetEnableCheckExposureOptimize(
          doc[kEnableCheckExposureOptimize].GetBool());
    }

    if (doc.HasMember(kEnableDisexposureWhenLynxHidden) &&
        doc[kEnableDisexposureWhenLynxHidden].IsBool()) {
      page_config->SetEnableDisexposureWhenLynxHidden(
          doc[kEnableDisexposureWhenLynxHidden].GetBool());
    }

    if (doc.HasMember(kEnableExposureWhenLayout) &&
        doc[kEnableExposureWhenLayout].IsBool()) {
      page_config->SetEnableExposureWhenLayout(
          doc[kEnableExposureWhenLayout].GetBool());
    }

    if (doc.HasMember(kEnableAirDetectRemovedKeysWhenUpdateData) &&
        doc[kEnableAirDetectRemovedKeysWhenUpdateData].IsBool()) {
      page_config->SetEnableAirDetectRemovedKeysWhenUpdateData(
          doc[kEnableAirDetectRemovedKeysWhenUpdateData].GetBool());
    }

    if (doc.HasMember(kEnableJSDataProcessor) &&
        doc[kEnableJSDataProcessor].IsBool()) {
      page_config->SetEnableDataProcessorOnJs(
          doc[kEnableJSDataProcessor].GetBool());
    }

    if (doc.HasMember(kEnableJsBindingApiThrowException) &&
        doc[kEnableJsBindingApiThrowException].IsBool()) {
      page_config->SetEnableJsBindingApiThrowException(
          doc[kEnableJsBindingApiThrowException].GetBool());
    } else if (lynx::tasm::Config::IsHigherOrEqual(target_sdk_version,
                                                   LYNX_VERSION_2_14)) {
      page_config->SetEnableJsBindingApiThrowException(true);
    }

    if (doc.HasMember(kEnableBindICU) && doc[kEnableBindICU].IsBool()) {
      page_config->SetEnableBindICU(doc[kEnableBindICU].GetBool());
    }

    if (doc.HasMember(kEnableQueryComponentSync) &&
        doc[kEnableQueryComponentSync].IsBool()) {
      page_config->SetEnableQueryComponentSync(
          doc[kEnableQueryComponentSync].GetBool());
    }

    if (doc.HasMember(kEnableAsyncFlushSubtree) &&
        doc[kEnableAsyncFlushSubtree].IsBool()) {
      page_config->SetEnableAsyncResolveSubtree(
          doc[kEnableAsyncFlushSubtree].GetBool() ? TernaryBool::TRUE_VALUE
                                                  : TernaryBool::FALSE_VALUE);
    }

    if (doc.HasMember(kAbsoluteInContentBound) &&
        doc[kAbsoluteInContentBound].IsBool()) {
      page_config->SetAbsoluteInContentBound(
          doc[kAbsoluteInContentBound].GetBool());
    }

    if (doc.HasMember(kEnableFixedNew) && doc[kEnableFixedNew].IsBool()) {
      page_config->SetEnableFixedNew(doc[kEnableFixedNew].GetBool());
    }

    if (doc.HasMember(kEnableCSSInheritance) &&
        doc[kEnableCSSInheritance].IsBool()) {
      page_config->SetEnableCSSInheritance(
          doc[kEnableCSSInheritance].GetBool());
    }

    if (doc.HasMember(kCSSAlignWithLegacyW3C) &&
        doc[kCSSAlignWithLegacyW3C].IsBool()) {
      page_config->SetCSSAlignWithLegacyW3C(
          doc[kCSSAlignWithLegacyW3C].GetBool());
    }

    if (doc.HasMember(kEnableCSSStrictMode) &&
        doc[kEnableCSSStrictMode].IsBool()) {
      page_config->SetEnableCSSStrictMode(doc[kEnableCSSStrictMode].GetBool());
    }

    if (doc.HasMember(kUnifyVWVHBehavior) && doc[kUnifyVWVHBehavior].IsBool()) {
      page_config->SetUnifyVWVH(doc[kUnifyVWVHBehavior].GetBool());
    } else if (lynx::tasm::Config::IsHigherOrEqual(target_sdk_version,
                                                   LYNX_VERSION_2_3)) {
      page_config->SetUnifyVWVH(true);
    }

    if (doc.HasMember(kFontScaleEffectiveOnlyOnSp) &&
        doc[kFontScaleEffectiveOnlyOnSp].IsBool()) {
      page_config->SetFontScaleSpOnly(
          doc[kFontScaleEffectiveOnlyOnSp].GetBool());
    }

    if (doc.HasMember(kEnableNewIntersectionObserver) &&
        doc[kEnableNewIntersectionObserver].IsBool()) {
      page_config->SetEnableNewIntersectionObserver(
          doc[kEnableNewIntersectionObserver].GetBool());
    }

    if (doc.HasMember(kIncludeFontPadding) &&
        doc[kIncludeFontPadding].IsBool()) {
      page_config->SetIncludeFontPadding(doc[kIncludeFontPadding].GetBool());
    }

    if (doc.HasMember(kEnableMultiTouch) && doc[kEnableMultiTouch].IsBool()) {
      page_config->SetEnableMultiTouch(doc[kEnableMultiTouch].GetBool());
    }

    if (doc.HasMember(kEnableHarmonyVisibleAreaChangeForExposure) &&
        doc[kEnableHarmonyVisibleAreaChangeForExposure].IsBool()) {
      page_config->SetEnableHarmonyVisibleAreaChangeForExposure(
          doc[kEnableHarmonyVisibleAreaChangeForExposure].GetBool());
    }
  };
};
}  // namespace tasm
}  // namespace lynx
#endif  // CORE_TEMPLATE_BUNDLE_TEMPLATE_CODEC_BINARY_DECODER_LYNX_CONFIG_DECODER_H_
