name: issue_management
on:
  issues:
    types:
      - opened
      - assigned

permissions:
  issues: write

jobs:
  add-label-triage:
    timeout-minutes: 30
    runs-on: lynx-ubuntu-22.04-mini
    if: github.event.action == 'opened' # Only run for 'opened' event
    steps:
      - name: Add 'status:need triage' label to new issues
        uses: actions-ecosystem/action-add-labels@bd52874380e3909a1ac983768df6976535ece7f8
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          labels: status:need triage

  update-label-assigned:
    timeout-minutes: 30
    runs-on: lynx-ubuntu-22.04-mini
    if: github.event.action == 'assigned' # Only run for 'assigned' event
    steps:
      # We won't check if the label exists. We are counting on the robustness of the actions.
      - name: Remove 'status:need triage' label
        uses: actions-ecosystem/action-remove-labels@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          labels: status:need triage

      - name: Add 'status:assigned' label
        uses: actions-ecosystem/action-add-labels@bd52874380e3909a1ac983768df6976535ece7f8
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          labels: status:assigned
